#if !canImport(ObjectiveC)
import XCTest

extension CommonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommonTests = [
        ("testCharacterParser", testCharacterParser),
        ("testElementParser", testElementParser),
        ("testEquatableElementParser", testEquatableElementParser),
        ("testEquatableSequenceParser", testEquatableSequenceParser),
        ("testRegularExpressionParser", testRegularExpressionParser),
        ("testSubstringParser", testSubstringParser),
    ]
}

extension ParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTests = [
        ("testAnyParser", testAnyParser),
        ("testCatchParser", testCatchParser),
        ("testCombineParser", testCombineParser),
        ("testEitherParser", testEitherParser),
        ("testForwardParser", testForwardParser),
        ("testManyParser", testManyParser),
        ("testOneOrManyParser", testOneOrManyParser),
        ("testOptionalParser", testOptionalParser),
        ("testSurroundedParser", testSurroundedParser),
        ("testTransformParser", testTransformParser),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommonTests.__allTests__CommonTests),
        testCase(ParserTests.__allTests__ParserTests),
    ]
}
#endif
